# Generated by Django 4.1.4 on 2022-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidevisits',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sidevisits',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sidevisits',
            name='country_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
