# Generated by Django 4.1.4 on 2022-12-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
