# Generated by Django 4.1.4 on 2022-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_deploy',
            field=models.URLField(default=''),
        ),
    ]
